### ISSUE TITLE
Game no longer loads

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#737]
"stackTrace":"TypeError: Cannot read property 'stats' of undefined\n    at ctor (https://irsr.games.pitforest.de/game.min.js:3221:512)\n    at c.<anonymous> (https://irsr.games.pitforest.de/game.min.js:101:328)\n    at new c (https://irsr.games.pitforest.de/game.min.js:100:166)\n    at c.onEnter (https://irsr.games.pitforest.de/game.min.js:3223:95)\n    at c.<anonymous> (https://irsr.games.pitforest.de/game.min.js:101:328)\n    at c.setNextScene (https://irsr.games.pitforest.de/game.min.js:531:392)\n    at c.drawScene (https://irsr.games.pitforest.de/game.min.js:525:245)\n    at c.mainLoop (https://irsr.games.pitforest.de/game.min.js:536:250)\n    at runUpdates (https://irsr.games.pitforest.de/game.min.js:3110:124)\n    at Worker.updateWorker.onmessage (https://irsr.games.pitforest.de/game.min.js:3110:462)","logs":"{\"log\":[]}","version":"1.4.1","versionNum":39,"errorMessage":"Cannot read property 'stats' of undefined"

**Comment by cpritchard** [comment]
game is already loading again not sure what was happening but provided relivant part of error report.
